# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
require "layouts_extension"
Gem::Specification.new do |s|
  s.name = %q{trusty-layouts-extension}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Sipple", "Michael Klett", "Jim Gay", "William Ross", "Tony Issakov", "Dirk Kelly"]
  s.date = %q{2014-10-06}
  s.description = %q{Extends Trusty CMS Layouts to support nesting, sharing with Rails Controllers and rendering HAML}
  s.email = %q{sipple@trustarts.org}
  s.homepage = %q{https://github.com/pgharts/trusty-share-layouts-extension}
  s.summary = %q{Extends Trusty CMS Layouts to support nesting, sharing with Rails Controllers and rendering HAML}
  s.extra_rdoc_files = [
    "README.md"
  ]
  ignores = if File.exist?('.gitignore')
              File.read('.gitignore').split("\n").inject([]) {|a,p| a + Dir[p] }
            else
              []
            end
  s.files         = Dir['**/*'] - ignores
  s.test_files    = Dir['test/**/*','spec/**/*','features/**/*'] - ignores
  # s.executables   = Dir['bin/*'] - ignores
  s.require_paths = ["lib"]

  gem.add_dependency 'trusty-cms',                     '>= 1.0.0'

end

